# Generated by Django 5.2.10 on 2026-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('MANHA', 'Manhã (6h)'), ('TARDE', 'Tarde (6h)'), ('DIURNO', 'Manhã + Tarde (12h)'), ('NOITE', 'Noite (12h)')], max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('atravessa_dia', models.BooleanField(default=False, help_text='Indica se o turno termina no dia seguinte')),
            ],
        ),
    ]
