# Generated by Django 5.2.10 on 2026-01-21 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data de início do turno')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='escalas.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'turno__hora_inicio'],
                'indexes': [models.Index(fields=['data'], name='escalas_esc_data_826af7_idx')],
            },
        ),
    ]
